internal sealed class SchemaNames // TypeDefIndex: 2281
{
	private XmlNameTable nameTable; 
	public string NsDataType; 
	public string NsDataTypeAlias; 
	public string NsDataTypeOld; 
	public string NsXml; 
	public string NsXmlNs; 
	public string NsXdr; 
	public string NsXdrAlias; 
	public string NsXs; 
	public string NsXsi; 
	public string XsiType; 
	public string XsiNil; 
	public string XsiSchemaLocation; 
	public string XsiNoNamespaceSchemaLocation; 
	public string XsdSchema; 
	public string XdrSchema; 
	public XmlQualifiedName QnPCData; 
	public XmlQualifiedName QnXml; 
	public XmlQualifiedName QnXmlNs; 
	public XmlQualifiedName QnDtDt; 
	public XmlQualifiedName QnXmlLang; 
	public XmlQualifiedName QnName; 
	public XmlQualifiedName QnType; 
	public XmlQualifiedName QnMaxOccurs; 
	public XmlQualifiedName QnMinOccurs; 
	public XmlQualifiedName QnInfinite; 
	public XmlQualifiedName QnModel; 
	public XmlQualifiedName QnOpen; 
	public XmlQualifiedName QnClosed; 
	public XmlQualifiedName QnContent; 
	public XmlQualifiedName QnMixed; 
	public XmlQualifiedName QnEmpty; 
	public XmlQualifiedName QnEltOnly; 
	public XmlQualifiedName QnTextOnly; 
	public XmlQualifiedName QnOrder; 
	public XmlQualifiedName QnSeq; 
	public XmlQualifiedName QnOne; 
	public XmlQualifiedName QnMany; 
	public XmlQualifiedName QnRequired; 
	public XmlQualifiedName QnYes; 
	public XmlQualifiedName QnNo; 
	public XmlQualifiedName QnString; 
	public XmlQualifiedName QnID; 
	public XmlQualifiedName QnIDRef; 
	public XmlQualifiedName QnIDRefs; 
	public XmlQualifiedName QnEntity; 
	public XmlQualifiedName QnEntities; 
	public XmlQualifiedName QnNmToken; 
	public XmlQualifiedName QnNmTokens; 
	public XmlQualifiedName QnEnumeration; 
	public XmlQualifiedName QnDefault; 
	public XmlQualifiedName QnXdrSchema; 
	public XmlQualifiedName QnXdrElementType; 
	public XmlQualifiedName QnXdrElement; 
	public XmlQualifiedName QnXdrGroup; 
	public XmlQualifiedName QnXdrAttributeType; 
	public XmlQualifiedName QnXdrAttribute; 
	public XmlQualifiedName QnXdrDataType; 
	public XmlQualifiedName QnXdrDescription; 
	public XmlQualifiedName QnXdrExtends; 
	public XmlQualifiedName QnXdrAliasSchema; 
	public XmlQualifiedName QnDtType; 
	public XmlQualifiedName QnDtValues; 
	public XmlQualifiedName QnDtMaxLength; 
	public XmlQualifiedName QnDtMinLength; 
	public XmlQualifiedName QnDtMax; 
	public XmlQualifiedName QnDtMin; 
	public XmlQualifiedName QnDtMinExclusive; 
	public XmlQualifiedName QnDtMaxExclusive; 
	public XmlQualifiedName QnTargetNamespace; 
	public XmlQualifiedName QnVersion; 
	public XmlQualifiedName QnFinalDefault; 
	public XmlQualifiedName QnBlockDefault; 
	public XmlQualifiedName QnFixed; 
	public XmlQualifiedName QnAbstract; 
	public XmlQualifiedName QnBlock; 
	public XmlQualifiedName QnSubstitutionGroup; 
	public XmlQualifiedName QnFinal; 
	public XmlQualifiedName QnNillable; 
	public XmlQualifiedName QnRef; 
	public XmlQualifiedName QnBase; 
	public XmlQualifiedName QnDerivedBy; 
	public XmlQualifiedName QnNamespace; 
	public XmlQualifiedName QnProcessContents; 
	public XmlQualifiedName QnRefer; 
	public XmlQualifiedName QnPublic; 
	public XmlQualifiedName QnSystem; 
	public XmlQualifiedName QnSchemaLocation; 
	public XmlQualifiedName QnValue; 
	public XmlQualifiedName QnUse; 
	public XmlQualifiedName QnForm; 
	public XmlQualifiedName QnElementFormDefault; 
	public XmlQualifiedName QnAttributeFormDefault; 
	public XmlQualifiedName QnItemType; 
	public XmlQualifiedName QnMemberTypes; 
	public XmlQualifiedName QnXPath; 
	public XmlQualifiedName QnXsdSchema; 
	public XmlQualifiedName QnXsdAnnotation; 
	public XmlQualifiedName QnXsdInclude; 
	public XmlQualifiedName QnXsdImport; 
	public XmlQualifiedName QnXsdElement; 
	public XmlQualifiedName QnXsdAttribute; 
	public XmlQualifiedName QnXsdAttributeGroup; 
	public XmlQualifiedName QnXsdAnyAttribute; 
	public XmlQualifiedName QnXsdGroup; 
	public XmlQualifiedName QnXsdAll; 
	public XmlQualifiedName QnXsdChoice; 
	public XmlQualifiedName QnXsdSequence; 
	public XmlQualifiedName QnXsdAny; 
	public XmlQualifiedName QnXsdNotation; 
	public XmlQualifiedName QnXsdSimpleType; 
	public XmlQualifiedName QnXsdComplexType; 
	public XmlQualifiedName QnXsdUnique; 
	public XmlQualifiedName QnXsdKey; 
	public XmlQualifiedName QnXsdKeyRef; 
	public XmlQualifiedName QnXsdSelector; 
	public XmlQualifiedName QnXsdField; 
	public XmlQualifiedName QnXsdMinExclusive; 
	public XmlQualifiedName QnXsdMinInclusive; 
	public XmlQualifiedName QnXsdMaxInclusive; 
	public XmlQualifiedName QnXsdMaxExclusive; 
	public XmlQualifiedName QnXsdTotalDigits; 
	public XmlQualifiedName QnXsdFractionDigits; 
	public XmlQualifiedName QnXsdLength; 
	public XmlQualifiedName QnXsdMinLength; 
	public XmlQualifiedName QnXsdMaxLength; 
	public XmlQualifiedName QnXsdEnumeration; 
	public XmlQualifiedName QnXsdPattern; 
	public XmlQualifiedName QnXsdDocumentation; 
	public XmlQualifiedName QnXsdAppinfo; 
	public XmlQualifiedName QnSource; 
	public XmlQualifiedName QnXsdComplexContent; 
	public XmlQualifiedName QnXsdSimpleContent; 
	public XmlQualifiedName QnXsdRestriction; 
	public XmlQualifiedName QnXsdExtension; 
	public XmlQualifiedName QnXsdUnion; 
	public XmlQualifiedName QnXsdList; 
	public XmlQualifiedName QnXsdWhiteSpace; 
	public XmlQualifiedName QnXsdRedefine; 
	public XmlQualifiedName QnXsdAnyType; 
	internal XmlQualifiedName[] TokenToQName; 


	public void .ctor(XmlNameTable nameTable) { }

	public void CreateTokenToQNameTable() { }

	public SchemaType SchemaTypeFromRoot(string localName, string ns) { }

	public bool IsXSDRoot(string localName, string ns) { }

	public bool IsXDRRoot(string localName, string ns) { }

}

public enum SchemaNames.Token // TypeDefIndex: 2282
{
	public int value__; 
	public const SchemaNames.Token Empty = 0;
	public const SchemaNames.Token SchemaName = 1;
	public const SchemaNames.Token SchemaType = 2;
	public const SchemaNames.Token SchemaMaxOccurs = 3;
	public const SchemaNames.Token SchemaMinOccurs = 4;
	public const SchemaNames.Token SchemaInfinite = 5;
	public const SchemaNames.Token SchemaModel = 6;
	public const SchemaNames.Token SchemaOpen = 7;
	public const SchemaNames.Token SchemaClosed = 8;
	public const SchemaNames.Token SchemaContent = 9;
	public const SchemaNames.Token SchemaMixed = 10;
	public const SchemaNames.Token SchemaEmpty = 11;
	public const SchemaNames.Token SchemaElementOnly = 12;
	public const SchemaNames.Token SchemaTextOnly = 13;
	public const SchemaNames.Token SchemaOrder = 14;
	public const SchemaNames.Token SchemaSeq = 15;
	public const SchemaNames.Token SchemaOne = 16;
	public const SchemaNames.Token SchemaMany = 17;
	public const SchemaNames.Token SchemaRequired = 18;
	public const SchemaNames.Token SchemaYes = 19;
	public const SchemaNames.Token SchemaNo = 20;
	public const SchemaNames.Token SchemaString = 21;
	public const SchemaNames.Token SchemaId = 22;
	public const SchemaNames.Token SchemaIdref = 23;
	public const SchemaNames.Token SchemaIdrefs = 24;
	public const SchemaNames.Token SchemaEntity = 25;
	public const SchemaNames.Token SchemaEntities = 26;
	public const SchemaNames.Token SchemaNmtoken = 27;
	public const SchemaNames.Token SchemaNmtokens = 28;
	public const SchemaNames.Token SchemaEnumeration = 29;
	public const SchemaNames.Token SchemaDefault = 30;
	public const SchemaNames.Token XdrRoot = 31;
	public const SchemaNames.Token XdrElementType = 32;
	public const SchemaNames.Token XdrElement = 33;
	public const SchemaNames.Token XdrGroup = 34;
	public const SchemaNames.Token XdrAttributeType = 35;
	public const SchemaNames.Token XdrAttribute = 36;
	public const SchemaNames.Token XdrDatatype = 37;
	public const SchemaNames.Token XdrDescription = 38;
	public const SchemaNames.Token XdrExtends = 39;
	public const SchemaNames.Token SchemaXdrRootAlias = 40;
	public const SchemaNames.Token SchemaDtType = 41;
	public const SchemaNames.Token SchemaDtValues = 42;
	public const SchemaNames.Token SchemaDtMaxLength = 43;
	public const SchemaNames.Token SchemaDtMinLength = 44;
	public const SchemaNames.Token SchemaDtMax = 45;
	public const SchemaNames.Token SchemaDtMin = 46;
	public const SchemaNames.Token SchemaDtMinExclusive = 47;
	public const SchemaNames.Token SchemaDtMaxExclusive = 48;
	public const SchemaNames.Token SchemaTargetNamespace = 49;
	public const SchemaNames.Token SchemaVersion = 50;
	public const SchemaNames.Token SchemaFinalDefault = 51;
	public const SchemaNames.Token SchemaBlockDefault = 52;
	public const SchemaNames.Token SchemaFixed = 53;
	public const SchemaNames.Token SchemaAbstract = 54;
	public const SchemaNames.Token SchemaBlock = 55;
	public const SchemaNames.Token SchemaSubstitutionGroup = 56;
	public const SchemaNames.Token SchemaFinal = 57;
	public const SchemaNames.Token SchemaNillable = 58;
	public const SchemaNames.Token SchemaRef = 59;
	public const SchemaNames.Token SchemaBase = 60;
	public const SchemaNames.Token SchemaDerivedBy = 61;
	public const SchemaNames.Token SchemaNamespace = 62;
	public const SchemaNames.Token SchemaProcessContents = 63;
	public const SchemaNames.Token SchemaRefer = 64;
	public const SchemaNames.Token SchemaPublic = 65;
	public const SchemaNames.Token SchemaSystem = 66;
	public const SchemaNames.Token SchemaSchemaLocation = 67;
	public const SchemaNames.Token SchemaValue = 68;
	public const SchemaNames.Token SchemaSource = 69;
	public const SchemaNames.Token SchemaAttributeFormDefault = 70;
	public const SchemaNames.Token SchemaElementFormDefault = 71;
	public const SchemaNames.Token SchemaUse = 72;
	public const SchemaNames.Token SchemaForm = 73;
	public const SchemaNames.Token XsdSchema = 74;
	public const SchemaNames.Token XsdAnnotation = 75;
	public const SchemaNames.Token XsdInclude = 76;
	public const SchemaNames.Token XsdImport = 77;
	public const SchemaNames.Token XsdElement = 78;
	public const SchemaNames.Token XsdAttribute = 79;
	public const SchemaNames.Token xsdAttributeGroup = 80;
	public const SchemaNames.Token XsdAnyAttribute = 81;
	public const SchemaNames.Token XsdGroup = 82;
	public const SchemaNames.Token XsdAll = 83;
	public const SchemaNames.Token XsdChoice = 84;
	public const SchemaNames.Token XsdSequence = 85;
	public const SchemaNames.Token XsdAny = 86;
	public const SchemaNames.Token XsdNotation = 87;
	public const SchemaNames.Token XsdSimpleType = 88;
	public const SchemaNames.Token XsdComplexType = 89;
	public const SchemaNames.Token XsdUnique = 90;
	public const SchemaNames.Token XsdKey = 91;
	public const SchemaNames.Token XsdKeyref = 92;
	public const SchemaNames.Token XsdSelector = 93;
	public const SchemaNames.Token XsdField = 94;
	public const SchemaNames.Token XsdMinExclusive = 95;
	public const SchemaNames.Token XsdMinInclusive = 96;
	public const SchemaNames.Token XsdMaxExclusive = 97;
	public const SchemaNames.Token XsdMaxInclusive = 98;
	public const SchemaNames.Token XsdTotalDigits = 99;
	public const SchemaNames.Token XsdFractionDigits = 100;
	public const SchemaNames.Token XsdLength = 101;
	public const SchemaNames.Token XsdMinLength = 102;
	public const SchemaNames.Token XsdMaxLength = 103;
	public const SchemaNames.Token XsdEnumeration = 104;
	public const SchemaNames.Token XsdPattern = 105;
	public const SchemaNames.Token XsdDocumentation = 106;
	public const SchemaNames.Token XsdAppInfo = 107;
	public const SchemaNames.Token XsdComplexContent = 108;
	public const SchemaNames.Token XsdComplexContentExtension = 109;
	public const SchemaNames.Token XsdComplexContentRestriction = 110;
	public const SchemaNames.Token XsdSimpleContent = 111;
	public const SchemaNames.Token XsdSimpleContentExtension = 112;
	public const SchemaNames.Token XsdSimpleContentRestriction = 113;
	public const SchemaNames.Token XsdSimpleTypeList = 114;
	public const SchemaNames.Token XsdSimpleTypeRestriction = 115;
	public const SchemaNames.Token XsdSimpleTypeUnion = 116;
	public const SchemaNames.Token XsdWhitespace = 117;
	public const SchemaNames.Token XsdRedefine = 118;
	public const SchemaNames.Token SchemaItemType = 119;
	public const SchemaNames.Token SchemaMemberTypes = 120;
	public const SchemaNames.Token SchemaXPath = 121;
	public const SchemaNames.Token XmlLang = 122;

}

