public class SideObjectLog // TypeDefIndex: 7248
{	public string version; // 0x10
	public string name; // 0x18
	public double id; // 0x20
	public double timestamp; // 0x28
	public int objectType; // 0x30
	public string gameobjectGUID; // 0x38
	public string textureGUID; // 0x40
	public float m_distance; // 0x48
	public float uvx; // 0x4C
	public float uvy; // 0x50
	public int position; // 0x54
	public float splinePosition; // 0x58
	public int selectedRotation; // 0x5C
	public float randomYAxisMinRotation; // 0x60
	public float randomYAxisMaxRotation; // 0x64
	public List<Vector2> nodeList; // 0x68
	public List<float> uvs; // 0x70
	public List<float> uvDistances; // 0x78
	public bool clampUVs; // 0x80
	public bool clampUVY; // 0x81
	public float clampUVYValue; // 0x84
	public bool terrainUVs; // 0x88
	public bool reverseUVs; // 0x89
	public float totalDistance; // 0x8C
	public List<bool> snapList; // 0x90
	public List<float> snapWeightList; // 0x98
	public List<Color> colorList; // 0xA0
	public string gameobjectStartGUID; // 0xA8
	public string gameobjectEndGUID; // 0xB0
	public int align; // 0xB8
	public int alignPoint; // 0xBC
	public bool weld; // 0xC0
	public bool combine; // 0xC1
	public bool combineInstantiated; // 0xC2
	public bool markerActive; // 0xC3
	public int uvType; // 0xC4
	public float uv; // 0xC8
	public bool randomObjects; // 0xCC
	public float forwardStartOffset; // 0xD0
	public float sidewaysOffset; // 0xD4
	public float density; // 0xD8
	public string goPath; // 0xE0
	public string startPath; // 0xE8
	public string endPath; // 0xF0
	public string texturePath; // 0xF8
	public int terrainTree; // 0x100
	public float minScale; // 0x104
	public float maxScale; // 0x108
	public bool childOrderActive; // 0x10C
	public int childOrder; // 0x110
	public bool meshBoundsAlignment; // 0x114
	public float xPosition; // 0x118
	public float xPosition2; // 0x11C
	public int relativeTo; // 0x120
	public float yPosition; // 0x124
	public float yRotation; // 0x128
	public float oldSidwaysDistance; // 0x12C
	public int sidewaysDistanceUpdate; // 0x130
	public float uvYRound; // 0x134
	public bool adjustUV; // 0x138
	public bool collider; // 0x139
	public bool boxcollider; // 0x13A
	public bool tangents; // 0x13B
	public GameObject sourceObject; // 0x140
	public bool flipMesh; // 0x148
	public GameObject startObject; // 0x150
	public GameObject endObject; // 0x158
	public GameObject connectionObject; // 0x160
	public Material material; // 0x168
	public List<ERMesh> meshObjects; // 0x170
	public Vector2 boxSize; // 0x178
	public Vector2 boxOffset; // 0x180
	public bool includeStartSegment; // 0x188
	public float startSegmentOffset; // 0x18C
	public bool includeStartEdgeTris; // 0x190
	public bool includeEndSegment; // 0x191
	public float endSegmentOffset; // 0x194
	public bool includeEndEdgeTris; // 0x198
	public bool adjustToRoadWidth; // 0x199
	public float xOffset; // 0x19C
	public float startOffset; // 0x1A0
	public float endOffset; // 0x1A4
	public float defaultStartOffset; // 0x1A8
	public float defaultEndOffset; // 0x1AC
	public float totalZDistance; // 0x1B0
	public float middleZDistance; // 0x1B4
	public float startZDistance; // 0x1B8
	public float endZDistance; // 0x1BC
	public float minStartZ; // 0x1C0
	public float maxStartZ; // 0x1C4
	public float minMiddleZ; // 0x1C8
	public float maxMiddleZ; // 0x1CC
	public float minEndZ; // 0x1D0
	public float maxEndZ; // 0x1D4
	public bool smoothStart; // 0x1D8
	public bool smoothMiddle; // 0x1D9
	public bool smoothEnd; // 0x1DA
	public GameObject targetObject; // 0x1E0
	public bool bridgeObject; // 0x1E8
	public bool tunnelObject; // 0x1E9
	public bool snapToTerrain; // 0x1EA
	public int layer; // 0x1EC
	public bool deformationObject; // 0x1F0
	public bool isStatic; // 0x1F1
	public bool castShadows; // 0x1F2
	public bool scaleToRoad; // 0x1F3
	public bool splitInBatches; // 0x1F4
	public Vector3 randomRotation; // 0x1F8
	public float randomMinRotation; // 0x204
	public float randomMaxRotation; // 0x208
	public float minRandomRotationDistance; // 0x20C
	public float maxRandomRotationDistance; // 0x210
	public float randomXPosition; // 0x214
	public float randomMinXPosition; // 0x218
	public float randomMaxXPosition; // 0x21C
	public float minRandomXPositionDistance; // 0x220
	public float maxRandomXPositionDistance; // 0x224
	public Vector3 boxColliderScale; // 0x228
	public float randomYPosition; // 0x234
	public float randomMinYPosition; // 0x238
	public float randomMaxYPosition; // 0x23C
	public float minRandomYPositionDistance; // 0x240
	public float maxRandomYPositionDistance; // 0x244
	public float bridgeHeight; // 0x248
	public int markerSplineController; // 0x24C
	public float bridgeLength; // 0x250
	public float deformationOffset; // 0x254
	public float markerIndent; // 0x258
	public float markerSurrounding; // 0x25C
	public bool indentController; // 0x260
	public bool excludeTerrainSplats; // 0x261
	public Vector3 scale; // 0x264
	public float indentExt; // 0x270
	public int category; // 0x274
	public Texture2D densityMap; // 0x278
	public float densitySize; // 0x280
	public float densitySize2; // 0x284
	public float densityStrength; // 0x288
	public float densityStrength2; // 0x28C
	public float terrainNormal; // 0x290
	public float terrainNormal2; // 0x294
	public List<ERChildsSO> childObjects; // 0x298
	public bool autoGenerate; // 0x2A0
	public float heightThreshold; // 0x2A4
	public float autogenerateStartOffset; // 0x2A8
	public float autogenerateEndOffset; // 0x2AC
	public bool snapIndents; // 0x2B0
	public float snapIndentWidth; // 0x2B4
	public bool cutHoles; // 0x2B8
	public float innerStartOffset; // 0x2BC
	public float innerEndOffset; // 0x2C0
	public bool ignoredForRetainingWalls; // 0x2C4
	public float heightMaxThreshold; // 0x2C8
	public float heightMaxStartThreshold; // 0x2CC
	public float heightMaxEndThreshold; // 0x2D0
	public float xThresholdDistance; // 0x2D4
	public float angleThreshold; // 0x2D8
	public int connectionRatio; // 0x2DC
	public bool retainingWall; // 0x2E0
	public int surroundingControl; // 0x2E4
	public int indentControl; // 0x2E8
	public List<Vector2> nodeListMirrored; // 0x2F0
	public List<float> uvsMirrored; // 0x2F8
	public List<float> snapWeightListMirrored; // 0x300
	public List<Color> colorListMirrored; // 0x308
	public bool hasVertexColors; // 0x310
	public float deformationOffsetForward; // 0x314
	public float deformationOffsetSideways; // 0x318
	public int connectionObjectRotation; // 0x31C
	public bool subMesh; // 0x320
	public bool acceptBarriers; // 0x321
	public bool activeOnBridges; // 0x322
	public bool dualSided; // 0x323
	public int mirrorType; // 0x324
	public bool snapVertexColors; // 0x328
	public float minSnapRange; // 0x32C
	public float maxSnapRange; // 0x330
	public bool clampUV4; // 0x334
	public float geoStartOffset; // 0x338
	public float geoEndOffset; // 0x33C
	public float startOverlapOffset; // 0x340
	public float endOverlapOffset; // 0x344
	public int lodLevels; // 0x348
	public List<bool> hardEdge; // 0x350
	public float hardEdgePadding; // 0x358
	public bool startEndCaps; // 0x35C
	public List<Vector2> endCapUVs; // 0x360
	public List<Vector2> startCapUVs; // 0x368
	public List<int> startCapTris; // 0x370
	public List<int> startCapTrisMirrored; // 0x378
	public Vector2 startCapUVOffset; // 0x380
	public Vector2 endCapUVOffset; // 0x388
	public float startCapUVScale; // 0x390
	public float endCapUVScale; // 0x394
	public float startCapUVRotation; // 0x398
	public float endCapUVRotation; // 0x39C
	public bool namedChilds; // 0x3A0
	public bool startSection; // 0x3A1
	public bool endSection; // 0x3A2
	public bool stepDown; // 0x3A3
	public bool stepUp; // 0x3A4
	public float stepDistance; // 0x3A8
	public float startDirZOffset; // 0x3AC
	public float endDirZOffset; // 0x3B0
	public bool buildOtherSideObject1; // 0x3B4
	public double defaultOtherSoId1; // 0x3B8
	public bool buildOtherSideObject2; // 0x3C0
	public double defaultOtherSoId2; // 0x3C8
	public List<double> buildOtherSideObjects; // 0x3D0
	public bool averageDistance; // 0x3D8
	public bool randomUVx; // 0x3D9
	public bool isUsedAsChild; // 0x3DA


	public void OODOOOQQCO(SideObject so) { }

	public void .ctor() { }

}

